### ISSUE TITLE
Disabling user apps doesn't work on 4.1 TW. (I think)

### ISSUE THREAD

**Issue by easyaspi314** [pylerSM/XInstaller#25]
I haven't tested this on vanilla, but there isn't any disable button, and additionally, it crashes with a NoSuchMethodError when you click force stop. This also happens with Native Freezer.

I suggest that you put a long click listener on the Uninstall button, or add a button itself. 

Samsung Galaxy S II Skyrocket (AT&T)
SGH-i727 
Stock 4.1.2 TouchWiz rooted

**Comment by pylerSM** [comment]
Show Xposed Log

**Comment by easyaspi314** [comment]
```
java.lang.NoSuchFieldError: com.android.settings.applications.InstalledAppDetails#mSpecialDisableButton
	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:611)
	at com.pyler.xinstaller.XInstaller$2.afterHookedMethod(XInstaller.java:175)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at com.android.settings.applications.InstalledAppDetails.initUninstallButtons(Native Method)
	at com.android.settings.applications.InstalledAppDetails.refreshButtons(InstalledAppDetails.java:919)
	at com.android.settings.applications.InstalledAppDetails.refreshUi(InstalledAppDetails.java:806)
	at com.android.settings.applications.InstalledAppDetails.onResume(InstalledAppDetails.java:604)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:874)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1814)
	at android.app.Activity.performResume(Activity.java:5261)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2629)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2667)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2140)
	at android.app.ActivityThread.access$700(ActivityThread.java:143)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4950)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
```

When I get to my laptop, I can send you the settings apk if you want.

**Comment by easyaspi314** [comment]
err. Yeah, I meant NoSuchFieldError.

**Comment by easyaspi314** [comment]
A browse through AOSP shows that mSpecialDisableButton and moreControlsButton were added in 4.2.

**Comment by pylerSM** [comment]
Ok. I will fix NoSuchFieldError.

**Comment by easyaspi314** [comment]
Maybe in 4.1 you can add a PopupMenu button instead.

Ok. I will fix NoSuchFieldError.

—
Reply to this email directly or view it on GitHub
<https://github.com/pylerSM/XInstaller/issues/25#issuecomment-148922542>.

**Comment by pylerSM** [comment]
simply hook initUninstallButtonsHook only for 4.2+

**Comment by pylerSM** [comment]
I have no 4.1 device so I am not able to do new things for 4.1.

**Comment by easyaspi314** [comment]
You know, the emulator is already rooted? But since you need to use ARM for
Xposed, it will be sloooow.
Anyways, I have a 4.1 device (I only have 4.1 devices), if you want me to
test something I can. I am a total noob to Xposed so I can't really help
much with the module.

simply hook initUninstallButtonsHook only for 4.2+

—
Reply to this email directly or view it on GitHub
<https://github.com/pylerSM/XInstaller/issues/25#issuecomment-149043680>.

**Comment by pylerSM** [comment]
I will fix this issue myself :)
